# Generated by Django 3.1.6 on 2021-05-23 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance', models.CharField(choices=[('150', 'Day'), ('200', 'Night'), ('250', 'Overnight')], max_length=50)),
                ('admit', models.IntegerField(default='1')),
                ('pricea', models.IntegerField(default='150')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.TextField()),
                ('expdate', models.DateField()),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cottage', models.TextField(choices=[('200', 'Small Kubo [5 pax]'), ('300', 'Big Kubo [10 pax]'), ('500', 'Cavana [11-20 pax]'), ('1000', 'Full Cavana [30 pax]')])),
                ('quant', models.IntegerField()),
                ('priceb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contact', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('card', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRH.card')),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort', models.TextField(choices=[('Tubigan Garden Resort', 'Tubigan'), ('Saniya Resort & Hotel', 'Saniya'), ('Coco Valley Richnez Waterpark', 'Coco Valley'), ('Volets Hotel & Resort', 'Volets')], default='none')),
                ('admission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRH.admission')),
                ('cottage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRH.cottage')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.DateField(null=True)),
                ('tot_amount', models.IntegerField(default='0')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRH.customer')),
                ('resortchosen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRH.resort')),
            ],
        ),
    ]
