# Generated by Django 3.1.6 on 2021-06-19 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=50, null=True)),
                ('cardnum', models.CharField(max_length=20, null=True)),
                ('expmonth', models.CharField(max_length=8, null=True)),
                ('expyear', models.CharField(max_length=4, null=True)),
                ('code', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('card', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRH.card')),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort', models.CharField(choices=[('Tubigan Garden Resort', 'Tubigan'), ('Saniya Resort & Hotel', 'Saniya'), ('Coco Valley Richnez Waterpark', 'Coco Valley'), ('Volets Hotel & Resort', 'Volets'), ('Jardin De Dasmarinas', 'Jardin'), ('V Resort Dasmarinas', 'V'), ('Palmas Del Sol Resort', 'Palmas Del Sol'), ('Riverside Resort', 'Riverside'), ('Qubo Qabana Resort', 'Qubo'), ('Kalipayan Resort', 'Kalipayan')], default='none', max_length=100)),
                ('entrance', models.CharField(choices=[('200', 'Day'), ('250', 'Night'), ('150', 'Day'), ('180', 'Night'), ('210', 'Overnight'), ('170', 'Day'), ('190', 'Night'), ('220', 'Overnight'), ('270', 'Day'), ('280', 'Night'), ('300', 'Overnight'), ('230', 'Day'), ('260', 'Night'), ('310', 'Overnight'), ('140', 'Day'), ('185', 'Night'), ('130', 'Day'), ('100', 'Day'), ('120', 'Night'), ('160', 'Overnight'), ('135', 'Day'), ('155', 'Night'), ('175', 'Overnight')], max_length=30)),
                ('admit', models.IntegerField(default='1')),
                ('pricea', models.IntegerField(default='100')),
                ('cottage', models.CharField(choices=[('750', 'Small Kubo (6 pax)'), ('1000', 'Medium Kubo (12 pax)'), ('1200', 'Large Kubo (15 pax)'), ('1250', 'Open Kubo (20 pax)'), ('900', 'Gazebo (9 pax)'), ('300', 'Gazebo (4 pax)'), ('500', 'Small Kubo (8 pax)'), ('600', 'Medium Kubo (10 pax)'), ('800', 'Large Kubo (15 pax)'), ('650', 'Peach Cottage (10 pax)'), ('1300', 'Violet Cottage (25 pax)'), ('400', 'Small Kubo (5 pax)'), ('670', 'Big Kubo (8-10 pax)'), ('700', 'Small Cavana (8 pax)'), ('1400', 'Kubo Cavana (10-12 pax)'), ('1800', 'Full Cavana (20 pax)'), ('350', 'Umbrella (4 pax)'), ('380', 'Short Table (6 pax)'), ('550', 'Petits Cottage (10 pax)'), ('850', 'Grande Cottage (20 pax)'), ('2000', 'Big Nipa Hut (30 pax)'), ('520', 'Regular Cottage (10 pax)'), ('1220', 'Big Cottage (25 pax)'), ('470', 'Bahay Kubo (2 pax)'), ('450', 'Regular Cottage (10 pax)'), ('630', 'Regular Cottage (16 pax)'), ('420', 'Small Kubo (8 pax)'), ('510', 'Big Kubo (10 pax)'), ('340', 'Tent (6 pax)'), ('330', 'Table with Umbrella (4 pax)'), ('460', 'Regular Cottage (15-20 pax)'), ('280', 'Table (8-10 pax)'), ('250', 'Umbrella (4 pax)'), ('1210', 'Family Kubo (20 pax)'), ('620', 'Kubo with sink (12 pax)'), ('310', 'Table (6 pax)')], max_length=100)),
                ('quant', models.IntegerField()),
                ('priceb', models.IntegerField()),
                ('tot_amount', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.DateField()),
                ('request', models.TextField(default='')),
                ('customer', models.ManyToManyField(to='TRH.Customer')),
                ('resortchosen', models.ManyToManyField(to='TRH.Resort')),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('0', 'Motorcycle'), ('50', 'Tricycle'), ('80', 'Jeepney'), ('150', 'Van'), ('200', 'Pickup Truck'), ('100', 'Sedan')], default='none', max_length=100)),
                ('licenseplate', models.CharField(default='none', max_length=13)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRH.customer')),
            ],
        ),
    ]
