# Generated by Django 3.1.6 on 2021-06-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='prkamnt',
            field=models.IntegerField(default='0'),
        ),
    ]
