# Generated by Django 3.1.6 on 2021-05-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tot_amount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.TextField(),
        ),
    ]
