# Generated by Django 3.1.6 on 2021-05-29 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='cottage',
        ),
        migrations.AddField(
            model_name='admission',
            name='resorts',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRH.resort'),
        ),
        migrations.AddField(
            model_name='cottage',
            name='resorts',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRH.resort'),
        ),
    ]
