# Generated by Django 3.1.6 on 2021-04-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='resort',
            field=models.CharField(choices=[('resorta', 'Tubigan Garden Resort'), ('resortb', 'Saniya Resort & Hotel'), ('resortc', 'Coco Valley Richnez Waterpark'), ('resortd', 'Volets Hotel & Resort')], default='none', max_length=10),
        ),
    ]
