# Generated by Django 3.1.6 on 2021-05-15 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRH.customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='resortchosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRH.resort'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='admission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRH.admission'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='cottage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRH.cottage'),
        ),
    ]
