# Generated by Django 3.1.6 on 2021-06-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='request',
        ),
    ]
