# Generated by Django 3.1.6 on 2021-05-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='code',
            field=models.IntegerField(max_length=3),
        ),
    ]
