# Generated by Django 3.1.6 on 2021-05-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0002_auto_20210515_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
