# Generated by Django 3.1.6 on 2021-04-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0002_item_resort'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='entrance',
            field=models.CharField(choices=[('entrancea', 'Day'), ('entranceb', 'Night'), ('entracec', 'Overnight')], default='none', max_length=10),
        ),
    ]
