# Generated by Django 3.1.6 on 2021-05-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0002_auto_20210529_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='entrance',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='cottage',
            field=models.TextField(),
        ),
    ]
