# Generated by Django 3.1.6 on 2021-05-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0002_auto_20210517_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='quant',
            field=models.IntegerField(default='100'),
        ),
    ]
