# Generated by Django 3.1.6 on 2021-06-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0002_parking_prkamnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='prkamnt',
        ),
        migrations.AlterField(
            model_name='parking',
            name='vehicle',
            field=models.CharField(choices=[('Motorcycle', 'Motorcycle'), ('Tricycle', 'Tricycle'), ('Jeepney', 'Jeepney'), ('Van', 'Van'), ('Pickup Truck', 'Pickup Truck'), ('Sedan', 'Sedan')], default='none', max_length=100),
        ),
    ]
