# Generated by Django 3.1.6 on 2021-05-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0003_auto_20210517_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='priceb',
            field=models.IntegerField(default='300'),
        ),
    ]
