# Generated by Django 3.1.6 on 2021-05-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0003_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='tot_amount',
            field=models.IntegerField(default='100'),
        ),
    ]
