# Generated by Django 3.1.6 on 2021-06-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0003_reservation_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='request',
            field=models.TextField(default=''),
        ),
    ]
