# Generated by Django 3.1.6 on 2021-05-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0003_auto_20210530_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='entrance',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='cottage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resort',
            name='resort',
            field=models.CharField(choices=[('Tubigan Garden Resort', 'Tubigan'), ('Saniya Resort & Hotel', 'Saniya'), ('Coco Valley Richnez Waterpark', 'Coco Valley'), ('Volets Hotel & Resort', 'Volets')], default='none', max_length=100),
        ),
    ]
