# Generated by Django 3.1.6 on 2021-04-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0003_item_entrance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='entrance',
            field=models.CharField(choices=[('entrancea', 'Day [Adult]'), ('entranceb', 'Night [Adult]'), ('entracec', 'Overnight [Adult')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='reserve',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
