# Generated by Django 3.1.6 on 2021-05-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0003_auto_20210531_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardnum',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expmonth',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expyear',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
