# Generated by Django 3.1.6 on 2021-06-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0003_auto_20210619_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='licenseplate',
            field=models.CharField(default='none', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='vehicle',
            field=models.CharField(choices=[('Motorcycle', 'Motorcycle'), ('Tricycle', 'Tricycle'), ('Jeepney', 'Jeepney'), ('Van', 'Van'), ('Pickup Truck', 'Pickup Truck'), ('Sedan', 'Sedan')], default='none', max_length=100, null=True),
        ),
    ]
