# Generated by Django 3.1.6 on 2021-05-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0004_auto_20210530_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='resort',
            field=models.CharField(max_length=100),
        ),
    ]
