# Generated by Django 3.1.6 on 2021-05-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0004_admission_tot_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='entrance',
            field=models.TextField(choices=[('Day', '150'), ('Night', '200'), ('Overnight', '250')]),
        ),
    ]
