# Generated by Django 3.1.6 on 2021-04-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0004_auto_20210425_1011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Info',
        ),
    ]
