# Generated by Django 3.1.6 on 2021-05-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0005_auto_20210530_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='resort',
            field=models.CharField(choices=[('Tubigan Garden Resort', 'Tubigan'), ('Saniya Resort & Hotel', 'Saniya'), ('Coco Valley Richnez Waterpark', 'Coco Valley'), ('Volets Hotel & Resort', 'Volets'), ('Jardin De Dasmarinas', 'Jardin'), ('V Resort Dasmarinas', 'V'), ('Palmas Del Sol Resort', 'Palmas Del Sol'), ('Riverside Resort', 'Riverside'), ('Qubo Qabana Resort', 'Qubo'), ('Kalipayan Resort', 'Kalipayan')], default='none', max_length=100),
        ),
    ]
