# Generated by Django 3.1.6 on 2021-06-19 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0005_auto_20210619_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRH.customer'),
        ),
    ]
