# Generated by Django 3.1.6 on 2021-05-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0005_auto_20210515_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='entrance',
            field=models.TextField(choices=[('150', 'Day'), ('200', 'Night'), ('250', 'Overnight')]),
        ),
    ]
