# Generated by Django 3.1.6 on 2021-05-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0006_auto_20210530_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='entrance',
            field=models.CharField(choices=[('200', 'Day'), ('200', 'Night'), ('150', 'Day'), ('180', 'Night'), ('180', 'Overnight'), ('150', 'Day')], max_length=30),
        ),
    ]
