# Generated by Django 3.1.6 on 2021-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0007_auto_20210515_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='tot_amount',
            field=models.IntegerField(default='0'),
        ),
    ]
