# Generated by Django 3.1.6 on 2021-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0007_auto_20210426_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='admit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
