# Generated by Django 3.1.6 on 2021-04-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0008_auto_20210426_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='admit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='entrance',
            field=models.CharField(choices=[('entrancea', 'Day [Adult]'), ('entranceb', 'Night [Adult]'), ('entracec', 'Overnight [Adult')], max_length=10),
        ),
    ]
