# Generated by Django 3.1.6 on 2021-05-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0009_auto_20210516_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='entrance',
            field=models.CharField(choices=[('150', 'Day'), ('200', 'Night'), ('250', 'Overnight')], max_length=50),
        ),
    ]
