# Generated by Django 3.1.6 on 2021-06-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0009_auto_20210620_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='suggest',
        ),
    ]
