# Generated by Django 3.1.6 on 2021-04-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0010_auto_20210426_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='admit',
            field=models.IntegerField(default='1'),
        ),
    ]
