# Generated by Django 3.1.6 on 2021-06-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0010_remove_reservation_suggest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='entrance',
            field=models.CharField(choices=[('200', 'Day'), ('250', 'Night'), ('210', 'Overnight')], max_length=30),
        ),
    ]
