# Generated by Django 3.1.6 on 2021-05-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0010_auto_20210516_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='entrance',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Overnight', 'Overnight')], max_length=50),
        ),
    ]
