# Generated by Django 3.1.6 on 2021-06-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0012_auto_20210620_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='vehicle',
            field=models.CharField(choices=[('10', 'Motorcycle'), ('20', 'Tricycle'), ('100', 'Jeepney'), ('200', 'Van'), ('250', 'Pickup Truck'), ('150', 'Sedan')], default='none', max_length=100, null=True),
        ),
    ]
