# Generated by Django 3.1.6 on 2021-05-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0012_auto_20210530_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='entrance',
            field=models.TextField(),
        ),
    ]
