# Generated by Django 3.1.6 on 2021-04-27 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0012_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='User',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TRH.user'),
        ),
    ]
