# Generated by Django 3.1.6 on 2021-06-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0013_auto_20210620_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='vehicle',
            field=models.CharField(choices=[('0', 'None'), ('10', 'Motorcycle'), ('20', 'Tricycle'), ('100', 'Jeepney'), ('200', 'Van'), ('250', 'Pickup Truck'), ('150', 'Sedan')], max_length=100, null=True),
        ),
    ]
