# Generated by Django 3.1.6 on 2021-04-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0014_auto_20210427_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='Visitor',
        ),
    ]
