# Generated by Django 3.1.6 on 2021-05-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0014_auto_20210530_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='cottage',
            field=models.CharField(choices=[('750', 'Small Kubo (6 pax)'), ('1000', 'Medium Kubo (12 pax)'), ('1200', 'Large Kubo (15 pax)'), ('1250', 'Open Kubo (20 pax)'), ('900', 'Gazebo (9 pax)'), ('300', 'Gazebo (4 pax)'), ('500', 'Small Kubo (8 pax)'), ('600', 'Medium Kubo (10 pax)'), ('800', 'Large Kubo (15 pax)'), ('650', 'Peach Cottage (10 pax)'), ('1300', 'Violet Cottage (25 pax)'), ('400', 'Small Kubo (5 pax)'), ('670', 'Big Kubo (8-10 pax)'), ('700', 'Small Cavana (8 pax)'), ('1400', 'Kubo Cavana (10-12 pax)'), ('1800', 'Full Cavana (20 pax)'), ('350', 'Umbrella (4 pax)'), ('380', 'Short Table (6 pax)'), ('550', 'Petits Cottage (10 pax)'), ('850', 'Grande Cottage (20 pax)'), ('2000', 'Big Nipa Hut (30 pax)'), ('520', 'Regular Cottage (10 pax)'), ('1220', 'Big Cottage (25 pax)'), ('470', 'Bahay Kubo (2 pax)'), ('450', 'Regular Cottage (10 pax)'), ('630', 'Regular Cottage (16 pax)'), ('420', 'Small Kubo (8 pax)'), ('510', 'Big Kubo (10 pax)'), ('340', 'Tent (6 pax)'), ('330', 'Table with Umbrella (4 pax)'), ('460', 'Regular Cottage (15-20 pax)'), ('280', 'Table (8-10 pax)'), ('250', 'Umbrella (4 pax)'), ('1210', 'Family Kubo (20 pax)'), ('620', 'Kubo with sink (12 pax)'), ('310', 'Table (6 pax)')], max_length=100),
        ),
    ]
