# Generated by Django 3.1.6 on 2021-05-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0015_auto_20210530_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='entrance',
            field=models.CharField(choices=[('200', 'Day'), ('250', 'Night'), ('150', 'Day'), ('180', 'Night'), ('210', 'Overnight'), ('170', 'Day'), ('190', 'Night'), ('220', 'Overnight'), ('270', 'Day'), ('280', 'Night'), ('300', 'Overnight'), ('230', 'Day'), ('260', 'Night'), ('310', 'Overnight'), ('140', 'Day'), ('185', 'Night'), ('130', 'Day'), ('100', 'Day'), ('120', 'Night'), ('160', 'Overnight'), ('135', 'Day'), ('155', 'Night'), ('175', 'Overnight')], max_length=30),
        ),
    ]
