# Generated by Django 3.1.6 on 2021-04-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0016_info_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='Visitor',
            new_name='User',
        ),
    ]
