# Generated by Django 3.1.6 on 2021-04-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRH', '0018_auto_20210428_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='User',
            new_name='visitor',
        ),
    ]
